name: Build steam_api64.dll

on:
  push:
    tags:
      - 'v*'  # билд запускается при пуше тега вида v1.0, v2.3 и т.п.

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build DLL
      run: cl /LD steam_api64_stub.cpp /Fe:steam_api64.dll

    - name: Zip output
      run: powershell Compress-Archive steam_api64.dll steam_api64.zip

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: steam_api64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
